export interface IjubAspirante {
    aspCodigo: number,
    aspCedula: String,
    aspUnidadEdu: string,
    aspRegimenLab: number,
    aspNomRegimenLab: string,
    aspPartidaInd: number,
    aspPartidaGen: string,
    aspModalidadCon: number,
    aspNomModalidadCon: string,
    aspCorreo: string,
    aspTelefono: string,
    aspDireccion: string,
    aspAportacionesPri: number,
    aspAportacionesPub: number,
    aspImpedimento: number,
    aspNomImpedimento: string,
    tipdisCodigo: number,
    parCodigo: number,
    tipdisPorcentaje: number,
    tipdisNomDiscapacidad: string,
    aspNumeroRes: string,
    aspEstado: number,
    tipjubNomJubilacion: string,
    jubParametro: any,
    aspFecha: string;
    listaEstadoTramite: any,
}
